# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: dockerhub.quantum.lrz.de/python-gcc-jre:3.11_12.1_17.0.14


# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PIP_EXTRA_INDEX_URL: "https://pypi.quantum.lrz.de/"
  PIP_TRUSTED_HOST: "pypi.quantum.lrz.de"
  QUANTUM_DS_HOST: "ldap://localhost:25334"
  QUANTUM_DB_FILENAME: "test_db.db"
  QUANTUM_DB_TESTING: "1"


# https://pip.pypa.io/en/stable/topics/caching/
cache:
  paths:
    - .cache/pip


before_script:
  - python --version ; pip --version  # For debugging
  - echo "$PIP_TRUSTED_HOST"
  - echo "$PIP_EXTRA_INDEX_URL"
  - pip install pdm
  - pdm info
  - pdm install



run-all-tests:
  stage: test
  script:
    - pdm run pytest
