# -----------------------------------------------------------------------------
# Test image
# -----------------------------------------------------------------------------
FROM python:3.11-slim-bookworm AS builder

ENV TZ="Europe/Berlin" \
    PYTHONUNBUFFERED=1 \
    PDM_VENV_IN_PROJECT=1 \
    PYTHONPATH=/mqp-dashboard-backend-test \
    PATH="/mqp-dashboard-backend-test/.venv/bin:$PATH"

# Set workdir
WORKDIR /mqp-dashboard-backend-test

# Install libraries
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    gcc \
    build-essential \
    python3-dev \
    libldap2-dev \
    libsasl2-dev \
    libssl-dev \
    sssd-ldap \
    slapd \
    ldap-utils \
    libldap-common \
    tox \
    lcov \
    valgrind \
    openjdk-17-jre \
    && rm -rf /var/lib/apt/lists/*

# Install PDM
RUN pip install --no-cache-dir pdm gunicorn
RUN pdm config python.use_venv true

# Copy dependency files
COPY gunicorn.conf.py pyproject.toml pdm.lock README.md ./

# Copy application
COPY mqp_dashboard_backend ./mqp_dashboard_backend
#COPY tests ./tests

# Install development dependencies
RUN pdm update

CMD ["pdm", "run", "gunicorn", "-c","gunicorn.conf.py"]
