services:
  mqp-dashboard-backend-server:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    platform: linux/amd64
    image: mqp-dashboard-backend:0.1.5
    container_name: mqp-dashboard-backend-server
    volumes:
      - ./mqp_dashboard_backend:/mqp-dashboard-backend-server/mqp_dashboard_backend
      - ./.env:/mqp-dashboard-backend-server/.env
    env_file:
      - .env
    environment:
      ENV: development
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
    restart: unless-stopped
