name: Continuous Integration

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsasl2-dev python3-dev libldap2-dev libssl-dev

      - name: Install uv and PDM
        run: python -m pip install --upgrade pip uv pdm

      - name: Install dependencies
        run: pdm install -G dev

      - name: Run Pylint
        run: uv run --active pylint mqp_dashboard_backend/

      - name: Run pre-commit
        run: uv run --active pre-commit run --all-files --config .pre-commit-config-ci.yaml

      - name: Run Pytest with coverage
        run: uv run --active python -m pytest tests

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
